# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "\
    swag init; \
    go build -o ./tmp/main .; \
  "
  bin = "./tmp/main"
  delay = 200 # ms
  exclude_dir = ["assets", "tmp", "vendor", "docs"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]