# .air.toml
root = "."
tmp_dir = "./tmp"
[build]
  cmd = """\
    swag init -o ./api; \
    go build -o ./tmp/main .; \
  """
  bin = "./tmp/main"
  delay = 200 # ms
  exclude_dir = ["assets", "tmp", "vendor", "api"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]