version: '3.8'
services:
    mariadb:
        image: mariadb:10.5.8
        restart: on-failure
        env_file: .env
        environment:
            - MYSQL_USER=$DB_USER
            - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
            - MYSQL_DATABASE=$DB_NAME
        ports:
            - $DB_LOCAL_PORT:$DB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
volumes:
    db:
