basePath: /api
definitions:
  models.Account:
    properties:
      createdAt:
        type: string
      email:
        type: string
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      password:
        type: string
      todos:
        items:
          $ref: '#/definitions/models.Todo'
        type: array
      tokenSecret:
        type: string
      updatedAt:
        type: string
    type: object
  models.Todo:
    properties:
      account:
        $ref: '#/definitions/models.Account'
      accountID:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
    type: object
  types.AuthResponse:
    properties:
      auth:
        $ref: '#/definitions/types.AuthResponseBody'
    type: object
  types.AuthResponseBody:
    properties:
      refreshToken:
        type: string
      token:
        type: string
    type: object
  types.LoginDTO:
    properties:
      account:
        $ref: '#/definitions/types.LoginDTOBody'
    type: object
  types.LoginDTOBody:
    properties:
      email:
        type: string
      password:
        maxLength: 100
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  types.RegisterDTO:
    properties:
      account:
        $ref: '#/definitions/types.RegisterDTOBody'
    type: object
  types.RegisterDTOBody:
    properties:
      email:
        type: string
      firstname:
        minLength: 2
        type: string
      lastname:
        minLength: 2
        type: string
      password:
        maxLength: 100
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  title: fiber-api
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Account'
            type: array
      summary: List accounts
      tags:
      - accounts
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Account'
      summary: Get account
      tags:
      - accounts
  /auth/login:
    put:
      consumes:
      - application/json
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/types.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AuthResponse'
      summary: Login
      tags:
      - auth
  /auth/refresh:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AuthResponse'
      summary: Refresh
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/types.RegisterDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AuthResponse'
      summary: Register
      tags:
      - auth
swagger: "2.0"
